services:
  spark-master:
    image: bitnami/spark:3.5.0
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./app.py:/app/app.py
      - ./sales_data.csv:/app/sales_data.csv
      - ./test.py:/app/test.py

  spark-worker-1:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8081:8081"
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8082:8081"
    depends_on:
      - spark-master
